language: php

sudo: false

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

php:
# - 5.5
 - 7.0

env:
 global:
  - MOODLE_BRANCH=MOODLE_31_STABLE
 matrix:
  - DB=pgsql
#  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config '$CFG->local_redislock_redis_server = "localhost";'
  - moodle-plugin-ci add-config 'define("LOCAL_REDISLOCK_REDIS_LOCK_TEST", "true");'
  - php moodle/admin/cli/purge_caches.php
  - redis-cli ping
  - redis-cli -h 127.0.0.1 -p 6379 ping

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
